# before applying this, make sure you have efs drivers installed in whereever you apply this manifest file
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-efs-file-system
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0871caaf72e84776b
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning"